//
//  LoginRouter.swift
//  Driver
//
//  Created by Behdad Keynejad on 7/17/1396 AP.
//  Copyright (c) 1396 AP Snapp. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates, edited by
//  Behdad Keynejad for Snapp, so you can apply clean architecture to your
//  iOS and Mac projects, see http://clean-swift.com
//

import UIKit

open class SNPRouter {
    // MARK: - Properties

    // MARK: - Methods
}
